### ISSUE TITLE
Kanban SetUp

### ISSUE THREAD

**Issue by Busiwa24** [Busiwa24/JS-Capstone-Project-#21]
https://github.com/Busiwa24/JS-Capstone-Project-/projects/1
In our project, we are two members of our team, Busiwa24, and mbdesigns1989.

**Comment by vichuge** [comment]
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your PR messages are descriptive ✔️

## Aspects to improve ♻️

- [ ] Please, assign the student for each card on the project. To be sure you did it, the card should looks like this:
![image](https://user-images.githubusercontent.com/20563252/134027709-b0463082-f5be-4977-8556-db8d5066cd27.png)

right now it looks like this (please, remember cards should be assigned to team members in a fair way):
![image](https://user-images.githubusercontent.com/20563252/134027786-a041c93f-7665-4cfc-bb7b-2e4e638e6d54.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by henatan99** [comment]
Hi @mbdesigns1989  && @Busiwa24 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ]There should be a circle with the user's avatar on each card as per the project requirement. See the example below
![image](https://user-images.githubusercontent.com/64894927/134043210-3041a84e-ad9f-475b-9e99-9b366720a236.png)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mbdesigns1989** [comment]
Hello Henok, there is an avatar assigned to each task, please check and explain, I don't want to repeat the module over this simple task, thanks.
Please, I'm stuck here.

**Comment by henatan99** [comment]
> Hello Henok, there is an avatar assigned to each task, please check and explain, I don't want to repeat the module over this simple task, thanks.
> Please, I'm stuck here.

Hi @mbdesigns1989 && @Busiwa24 , I am so sorry for the mistake. In fact, you made it right and I leave this message as a reminder for the next reviewer that the change I requested is by mistake. Kindly request another request and hopefully, it will be approved. :pray:

**Comment by carlos-ssh** [comment]
Hi @Busiwa24 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
